### ISSUE TITLE
ENH: Transfer helper functions from zoll-foundation-grant-project

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#107]
## Description

Those helper functions should probably be generalized and moved into some module in this project.

## Tasks

- [x] #125 
- [ ] Generalize `match_edisposition`
- [ ] `apply_categorizations` should take `Union[pd.DataFrame, list[pd.DataFrame]]`
- [ ] Transport helper functions
- [ ] Inter-facility helper functions

**Comment by Jython1415** [comment]
Closed as most of the helper functions are not in use anymore
