### ISSUE TITLE
VER: 0.1

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#134]
## Goals

- [x] Improve documentation
- [x] Clean up codebase
- [x] Improve development workflow

## Issues

- [x] #93 
- [x] #131 
- [x] #91 
- [x] #68 
- [x] #75 
- [x] #76 
- [x] #87 
- [x] #117 
  - Not sure if this is a valid issue or not, so the first step will be to investigate this
- [x] #115 
- [x] #110 
- [x] #105 

## Tasks

- [x] Review package information
- [x] Upload to test PyPI and make sure it looks alright
- [x] Create a script to publish to PyPI
- [x] Publish to PyPI

**Comment by Jython1415** [comment]
Edited the original comment to reduce the issues tracked by this version.

**Comment by Jython1415** [comment]
Changed version number because I don't need to be tracking such minor versions.

**Comment by Jython1415** [comment]
Finished all documentation issues.

**Comment by Jython1415** [comment]
Finished all blocking issues. Next tasks will be added to the original comment.

**Comment by Jython1415** [comment]
Scripts created with https://github.com/Jython1415/zolltools/commit/fe15dc8c020aaf26b12b30a5aed35540bffb2889

**Comment by Jython1415** [comment]
Set credentials with `keyring set https://test.pypi.org/legacy/ __token__`
