### ISSUE TITLE
ENH: Add location code grouping and parsing

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#27]
Add grouping and parsing of [Y92 location codes](https://www.aapc.com/codes/icd-10-codes/Y92) to this package by transferring and building on the module in the [zoll-foundation-grant-project](https://github.com/Jython1415/zoll-foundation-grant-project).

## Tasks

- [x] Transfer the code
- [x] Transfer Y92 data to the package
- [x] Add data to the package
- [x] Clean up existing methods

### Deferred

- [ ] #35

## Resources

- [Hatch -- Hatch configuration](https://hatch.pypa.io/latest/config/hatch/#data)
- [importlib documentation](https://docs.python.org/3/library/importlib.html#module-importlib.resources)
- [importlib.resources documentation](https://docs.python.org/3/library/importlib.resources.html#module-importlib.resources)
- [importlib.resources.abc.Traversable](https://docs.python.org/3/library/importlib.resources.abc.html#importlib.resources.abc.Traversable)

**Comment by Jython1415** [comment]
Referencing [Making a Python Package VI - including data files](https://kiwidamien.github.io/making-a-python-package-vi-including-data-files.html) by [Damien martin](https://kiwidamien.github.io/author/damien-martin.html) to include a data file with a mapping of the Y92 codes.

**Comment by Jython1415** [comment]
It turns out `pkg_resources` is an outdated approach. I am shifting to following [SetupTools -- Data Files Support](https://setuptools.pypa.io/en/stable/userguide/datafiles.html#include-package-data) instead.

**Comment by Jython1415** [comment]
[pypa/hatch issue #492](https://github.com/pypa/hatch/issues/492) provides an explanation of how to specify other directories to include in the package.

**Comment by Jython1415** [comment]
`importlib` to access data... consolidated resources under the first comment
