### ISSUE TITLE
ENH: Executable `locationcodes` module

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#39]
## Problem

There isn't a good way to use the `locationcodes` module to manage groupings without creating a notebook dedicated to this.

## Solution

Make `locationcodes` executable, and add command line arguments to *list* and *validate* groupings.

## Tasks

- [ ] Make locationcodes executable
- [ ] Add `--list` option
- [ ] Add `--validate` option
- [ ] Document `list` and `validate`

**Comment by Jython1415** [comment]
As mentioned in [#48 (comment)](https://github.com/Jython1415/zolltools/pull/48#issuecomment-1583708837) The `locationcode` module is executable and `init` and `list` commands have been created. `validate` and documentation are still not complete, but that will be done with another issue.
