### ISSUE TITLE
ENH: Add `zolltools.db.verify` module to verify correct installation

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#41]
## Problem

Hard to check on a new device is all files have been installed correctly.

## Solution

Simple command line tool to check that all files are downloaded

## Tasks

- [ ] Create a .pkl file with expected metadata for each `.parquet` file in the NEMSIS database
- [ ] Include the data file in the package
- [ ] Write the command line tool to read this data and compare it with the local installation

**Comment by Jython1415** [comment]
This is too fancy. Not worth the effort.
