### ISSUE TITLE
ENH: Add `validate` command to `locationcodes`

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#50]
## Problem

There is no easy way to validate a grouping of location codes.

## Solution

Create a command, `python -m locationcode validate [name-of-grouping]` that will check to see if the grouping includes all  Y92 codes.

## Tasks

- [x] #80
- [ ] Create a `validate` command (check for overlapping ids)
- [ ] Check existing groupings to see if the command works
- [ ] Add tests for `locationcodes validate`

**Comment by Jython1415** [comment]
Relinked the pull request to make it easier to find where I'm doing the work for this issue

**Comment by Jython1415** [comment]
Close as not planned.
