### ISSUE TITLE
DOC: Explain Y92 codes and link to resources in documentation for `locationcodes`

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#75]
## Tasks

- [ ] DOC: Create a wiki
- [ ] Add a section for `locationcodes`
- [ ] Add an explanation for Y92 codes

**Comment by Jython1415** [comment]
Note that zoll-foundation-grant-project has added a section for location codes, so the wiki for this repository can make reference to that instead of explaining everything again.

**Comment by Jython1415** [comment]
This part of the code is going to be refactored significantly, so it would be better to leave it undocumented for the time being.
