### ISSUE TITLE
CLN: Move grouping of null values to location code groupings instead of `to_description`

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#78]
## Problem

The following is in `to_description`

```python
if code == "7701001":
    return "Not Applicable"
elif code == "7701003":
    return "Not Recorded"
```

## Tasks

- [ ] Move the data to the location code groupings
- [ ] Remove the logic from `to_description`
- [ ] Update documentation to reflect this change

**Comment by Jython1415** [comment]
Location code grouping will be redone so closing this as not planned.
