### ISSUE TITLE
TST: Run tests with dependencies at various versions

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#79]
## Completion Criteria

- [ ] Determined whether this was a good idea
- [ ] Followed through with the decision for the above requirements

## Tasks

- [ ] Look into what other packages do for this

## Versions

```toml
dependencies = [
  "pandas>=0.4",
  "pyarrow>=2",
  "pyreadstat>=1.1.7",
]
```

**Comment by Jython1415** [comment]
Not worth the effort for this project.
