### ISSUE TITLE
ENH: `get_column_list` method for `pqtools`

### ISSUE THREAD

**Issue by Jython1415** [Jython1415/zolltools#90]
## Problems

It is currently not possible to figure out what columns are included in a table without loading the table (even just part of it) into memory.

## Solution

- [x] `pqtools.Reader.get_column_list(self, pq_name: str, tmp: bool = True)`
- Idea: #92

## Tasks

- [x] Tests to fail
- [x] Implementation
- [x] Clean and review
